name: Testing configuration varibales

on:
  workflow_dispatch

env:
  cloud: google-cloud

jobs:
  greetings_jobs:
    runs-on: ubuntu-latest
    env:
      Greetings: Hello
    steps:
      - name: "Say Hello to vishal"
        run: echo "$Greetings $First_Name is using $cloud with project ${{vars.PROJECT_ID}}!"
        env:
          First_Name: Gaurav
